# Generated by Django 2.1.5 on 2019-01-29 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=200)),
                ('gameYear', models.CharField(max_length=4)),
                ('gameInfo', models.URLField()),
                ('gameArtwork', models.ImageField(upload_to='artwork/')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreResult', models.IntegerField()),
                ('scoreTimeDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('scoreScreenShot', models.ImageField(upload_to='shots/%Y/%m/%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scoreGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Game')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gameSystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.System'),
        ),
    ]
